### ISSUE TITLE
Creating index with "ddoc":"" makes DB read-only

### ISSUE THREAD

**Issue by ermouth** [apache/couchdb#1472]
## Expected Behavior
CouchDB should prevent creation of Mango index ddoc with the `_design/` _id. 

## Current Behavior
POST-ing JSON body with `"ddoc":""` field to `/db/_index` creates a ddoc, which seems non-deletable, effectively breaks replication and makes DB non-writable (both PUT and POST fail with 500).

## Steps to Reproduce
1. Open Fauxton
2. Create a DB
3. Open Mango query tab and then Mango indexes
4. Create index with any name and `"ddoc":""` field

## Context
I was creating Mango index editor in Couch Photon, and noticed the issue during UI tests.

## Your Environment

* Version used: CouchDB 2.1.2 single node
* Browser Name and version: Chrome 66
* Operating System and version (desktop or mobile):  Xenial

**Comment by wohali** [comment]
@ermouth I *think* this was fixed for 2.2.0, see https://github.com/apache/couchdb/pull/961

**Comment by wohali** [comment]
if not let me know and we can reopen

**Comment by ermouth** [comment]
#961 is unrelated. Letting you know it is not fixed in 2.2.x branch. Just built 2.2.0 from sources to check it.

**Comment by nickva** [comment]
This still happens. With auto-indexer (ken) it's even worse as it will start crashing as well and flooding the logs with failures that look like:

```
[error] 2021-11-04T17:19:00.390502Z node1@127.0.0.1 emulator -------- Error in process <0.16318.0> on node 'node1@127.0.0.1' with exit value:
{{nocatch,{illegal_docid,<<"Illegal document id `_design/`">>}},[{couch_doc,validate_docid,1,[{file,"src/couch_doc.erl"},{line,213}]},{couch_doc,transfer_fields,3,[{file,"src/couch_doc.erl"},{line,252}]},{ken_server,'-update_db_indexes/2-fun-1-',4,[{file,"src/ken_server.erl"},{line,280}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{ken_server,update_db_indexes,2,[{file,"src/ken_server.erl"},{line,279}]}]}
```

**Comment by jaydoane** [comment]
It appears that https://github.com/apache/couchdb/pull/3990 fixes this issue, so closing as resolved.
