### ISSUE TITLE
main.cpp error when building from source

### ISSUE THREAD

**Issue by wa0nder** [apache/couchdb#5747]
I'm attempting to build CouchDB from source because I want a couchdb installation that is self-contained in a single folder on linux as with test builds. I am following these two links:

https://github.com/apache/couchdb/blob/main/INSTALL.Unix.md
https://cwiki.apache.org/confluence/display/COUCHDB/Testing+a+Source+Release

As a quick aside, Mozilla SpiderMonkey 60 no longer has all of the necessary .h files and I had to change the rebar.config.script file to directly use mozjs128 like so: "-I/usr/include/mozjs-128 -I/usr/local/include/mozjs-128" to get a successful ./configure run.

I have all of the dependencies installed already, successfully ran ./configure.

And then I ran 'make release' (also tried 'make check') and encountered these two errors:
```

Compiling /run/media/veracrypt2/couchdb/dist/apache-couchdb-3.5.1/src/couch/priv/couch_js/86/main.cpp
/run/media/veracrypt2/couchdb/dist/apache-couchdb-3.5.1/src/couch/priv/couch_js/86/main.cpp:51:1: error: too many initializers for â
   51 | };
      | ^
/run/media/veracrypt2/couchdb/dist/apache-couchdb-3.5.1/src/couch/priv/couch_js/86/main.cpp:257:1: error: invalid conversion from â {aka â} to â {aka â} [-fpermissive]
  257 | };
      | ^
      | |
      | bool (*)(JSContext*, JS::HandleString) {aka bool (*)(JSContext*, JS::Handle<JSString*>)}
```

line 51 in main.cpp is this:

```
static JSClassOps global_ops = {
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    JS_GlobalObjectTraceHook
};
```

Can someone far more knowledgeable in C++ explain what this is doing and what this error means? I tried looking up vectors, scalars, structs, and array initialization and experimented with running some alternate formats (e.g. adding []) in an online c++ compiler but I still don't know exactly what data structure is being initialized here and why it is breaking.  Thanks!

**Comment by nickva** [comment]
Not sure why you can't build it, we support these Spidermonkey versions:

https://github.com/apache/couchdb/blob/95fe2013a1205c4d6ae612be925153415e853b04/src/couch/rebar.config.script#L82-L107

I see 60 in there and but it requires specifying the version in the `./configure` command explicitly and requires having the mozjs dev library package installed (the include files, etc). For instance I can still build it with 1.8.5 with `./configure --spidermonkey-version 1.8.5`

If you can't install Spidermonkey, as we've struggled with it (due to C++ api changes, and then it got removed from some OS base package like RHEL 10), you can try using the built-in QuickJS view engine with `./configure --disable-spidermonkey`

**Comment by wa0nder** [comment]
@nickva that worked like a charm, thank you! For anyone else that arrives here weary from hours of troubleshooting spidermonkey versions here are the two steps

1. ./configure --disable-spidermonkey
2. make release
done!

Is there any reason couchdb doesn't release a standalone binary on the main download page? It already seems part of the build process and sure makes it easy to move and/or backup your DB to other partitions, storage devices, etc.

Also, not expected but for pure curiosity sake, it would be nice to know what about that c++ file is causing errors. I have gcc 15.2.1 installed; maybe I needed to use an older version of the compiler that recognized that syntax for initializing that data structure?

**Comment by nickva** [comment]
> Is there any reason couchdb doesn't release a standalone binary on the main download page? It already seems part of the build process and sure makes it easy to move and/or backup your DB to other partitions, storage devices, etc.

We provide binary packages for some OS-es: https://docs.couchdb.org/en/stable/install/unix.html. For some OS we'll provide QuickJS only versions (RHEL 10 is planned) which won't have a SM dependency. Now that still not a single standalone binary, but it's a bit closer.

> Also, not expected but for pure curiosity sake, it would be nice to know what about that c++ file is causing errors. I have gcc 15.2.1 installed; maybe I needed to use an older version of the compiler that recognized that syntax for initializing that data structure?

A new GCC version would make sense, yeah. A newer SM version could work perhaps, but only up to version 128 (140 is not supported see https://github.com/apache/couchdb/pull/5677).

**Comment by wa0nder** [comment]
I did see that link before and unfortunately I'm not on any of those distros. I tried finding the couchdb .deb file since .deb files usually have a standalone folder that can be extracted from the .deb and run but I couldn't get access to the Debian repository through a browser. Perhaps there's a direct way to grab it using curl but I didn't find how to do it.

In any case, I'll close this as solved, thanks again.

**Comment by big-r81** [comment]
Only for the record:

You did only `./configure` that means, the the build script is expecting SpiderMonkey v91 per default.
You used SpiderMonkey v128, which has different C++ apis as v91. Iirc with more entries in the `JSClassOps` object. Thats why you get the compiler errors.
If you want to build against v128 then you have to use: `./configure --spidermonkey-version 128` or as Nick mentioned, use QuickJS.

**Comment by wa0nder** [comment]
@big-r81 - appreciate the response! My mind will now stop nagging me about the error message 😃 

Also, if SpiderMonkey v91 is now the actual default, perhaps the INSTALL.Unix file's [dependencies](https://github.com/apache/couchdb/blob/main/INSTALL.Unix.md#dependencies) section should be updated to reflect this, it currently says 1.8.5 or 60 are the only two accepted versions; a quick link to the rebar.config.script showing all the supported versions would be helpful I think.
