### ISSUE TITLE
Fauxton doesn't handle well all design docs names (with special characters)

### ISSUE THREAD

**Issue by luanmm** [apache/couchdb#713]
I have some "special fields", in the fashion of firebase (that uses something like ".field" to reference something that is "a contract" of the database), where, in the name, there is some special characters (like the dollar sign "$"). In that cases, Fauxton doesn't let I expand the design document to edit/list.

![image](https://user-images.githubusercontent.com/1708808/28571706-86ea0394-711a-11e7-9247-f84d33298b0a.png)

## Expected Behavior

To work like any other design document. If it is a valid design document name for CouchDB, it must be for Fauxton. Plus, it could show the real character in Fauxton interface ("$"), but nowadays it is showing ( "%24"), that is the url-encoded one.

## Current Behavior

Fauxton doesn't accept all design document names that CouchDB supports.

## Possible Solution

Check why the script is throwing errors when some special character is used.

## Steps to Reproduce (for bugs)

1. Create a design document named "_design/$test".
2. Try to access it in Fauxton to add views or list/edit.
3. An error will output in console and nothing more will happen.

## Context

It is a valid use case to work with special characters in CouchDB. It is not so uncommon to have "special fields" or "special documents" that describe something that must be known only by the system as a "contract" or with a special meaning. In those cases, it is common to have more complex names (to distinct the special things from the normal things). And, if CouchDB handle well this scenarios, Fauxton could do it aswell.

## Your Environment

* Version used: Fauxton on Apache CouchDB v. 2.0.0
* Browser Name and version: Chrome 59.0.3071.115 (64 bits)
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: N/A

**Comment by luanmm** [comment]
Another possible issue with special characters (with Fauxton), is when a password have "@" on it. I haven't tried a lot of cases, but this must be a problem because of the typical HTTP "Basic" Auth connection strings.

As a suggestion, I would say to put special characters scenarios in testing cases on these contexts. It would be nice to keep tracking and to maintain compatible with CouchDB specs.

**Comment by wohali** [comment]
I believe this has been fixed since v2.0.0. Are you able to try one of our newer builds? 2.1.0 should release this week.

**Comment by luanmm** [comment]
I will try 2.1.0 when released, @wohali, and will update the status here. Thanks for the reply!

**Comment by wohali** [comment]
2.1.0 has been released, can you confirm it fixes your issues?

**Comment by luanmm** [comment]
Hello, @wohali.

First, sorry for delay this testing that much, but I was in a hurry because of other things that I've been doing since this issue report.

Today I have upgraded to CouchDB/Fauxton 2.1.0 and the problem persists.

**Comment by wohali** [comment]
Please open a bug over at apache/couchdb-fauxton.
